//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautytrend.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonDat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonDat()
        {
            this.PhieuMuas = new HashSet<PhieuMua>();
        }
    
        public int MaHoaDon { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string NguoiGui { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> Gia { get; set; }
        public string ChuY { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual user user { get; set; }
        public virtual UserAdmin UserAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMua> PhieuMuas { get; set; }
    }
}
