//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautytrend.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string Anh { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> MaUser { get; set; }
    
        public virtual UserAdmin UserAdmin { get; set; }
    }
}
