//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beautytrend.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.HoaDonDats = new HashSet<HoaDonDat>();
        }
    
        public int user_id { get; set; }
        public string email { get; set; }
        public string passwd { get; set; }
        public string name { get; set; }
        public Nullable<int> phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> lv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonDat> HoaDonDats { get; set; }
    }
}
